// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.16.3 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/labstack/echo/v4"
	"github.com/oapi-codegen/runtime"
)

// AssignAuthor defines model for AssignAuthor.
type AssignAuthor struct {
	AuthorId int `json:"author_id"`
}

// Author defines model for Author.
type Author struct {
	Bio  *string `json:"bio,omitempty"`
	Id   *int    `json:"id,omitempty"`
	Name *string `json:"name,omitempty"`
}

// Book defines model for Book.
type Book struct {
	Author        *Author `json:"author,omitempty"`
	AuthorId      *int    `json:"author_id,omitempty"`
	Id            *int    `json:"id,omitempty"`
	PublishedYear *int    `json:"published_year,omitempty"`
	Title         *string `json:"title,omitempty"`
}

// NewAuthor defines model for NewAuthor.
type NewAuthor struct {
	Bio  *string `json:"bio,omitempty"`
	Name string  `json:"name"`
}

// NewBook defines model for NewBook.
type NewBook struct {
	AuthorId      int    `json:"author_id"`
	PublishedYear *int   `json:"published_year,omitempty"`
	Title         string `json:"title"`
}

// ListAuthorsParams defines parameters for ListAuthors.
type ListAuthorsParams struct {
	Page  *int `form:"page,omitempty" json:"page,omitempty"`
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`
}

// ListBooksParams defines parameters for ListBooks.
type ListBooksParams struct {
	Page  *int `form:"page,omitempty" json:"page,omitempty"`
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`
}

// CreateAuthorJSONRequestBody defines body for CreateAuthor for application/json ContentType.
type CreateAuthorJSONRequestBody = NewAuthor

// UpdateAuthorJSONRequestBody defines body for UpdateAuthor for application/json ContentType.
type UpdateAuthorJSONRequestBody = NewAuthor

// CreateBookJSONRequestBody defines body for CreateBook for application/json ContentType.
type CreateBookJSONRequestBody = NewBook

// UpdateBookJSONRequestBody defines body for UpdateBook for application/json ContentType.
type UpdateBookJSONRequestBody = NewBook

// AssignAuthorToBookJSONRequestBody defines body for AssignAuthorToBook for application/json ContentType.
type AssignAuthorToBookJSONRequestBody = AssignAuthor

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// List all authors
	// (GET /authors)
	ListAuthors(ctx echo.Context, params ListAuthorsParams) error
	// Create an author
	// (POST /authors)
	CreateAuthor(ctx echo.Context) error
	// Delete an author
	// (DELETE /authors/{id})
	DeleteAuthor(ctx echo.Context, id int) error
	// Get an author by ID
	// (GET /authors/{id})
	GetAuthor(ctx echo.Context, id int) error
	// Update an author
	// (PUT /authors/{id})
	UpdateAuthor(ctx echo.Context, id int) error
	// Get all books by author
	// (GET /authors/{id}/books)
	GetBooksByAuthor(ctx echo.Context, id int) error
	// List all books
	// (GET /books)
	ListBooks(ctx echo.Context, params ListBooksParams) error
	// Create a book
	// (POST /books)
	CreateBook(ctx echo.Context) error
	// Delete a book
	// (DELETE /books/{id})
	DeleteBook(ctx echo.Context, id int) error
	// Get a book by ID
	// (GET /books/{id})
	GetBook(ctx echo.Context, id int) error
	// Update a book
	// (PUT /books/{id})
	UpdateBook(ctx echo.Context, id int) error
	// Assign author to book
	// (PUT /books/{id}/author)
	AssignAuthorToBook(ctx echo.Context, id int) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// ListAuthors converts echo context to params.
func (w *ServerInterfaceWrapper) ListAuthors(ctx echo.Context) error {
	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params ListAuthorsParams
	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameter("form", true, false, "page", ctx.QueryParams(), &params.Page)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter page: %s", err))
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", ctx.QueryParams(), &params.Limit)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter limit: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ListAuthors(ctx, params)
	return err
}

// CreateAuthor converts echo context to params.
func (w *ServerInterfaceWrapper) CreateAuthor(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.CreateAuthor(ctx)
	return err
}

// DeleteAuthor converts echo context to params.
func (w *ServerInterfaceWrapper) DeleteAuthor(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id int

	err = runtime.BindStyledParameterWithLocation("simple", false, "id", runtime.ParamLocationPath, ctx.Param("id"), &id)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.DeleteAuthor(ctx, id)
	return err
}

// GetAuthor converts echo context to params.
func (w *ServerInterfaceWrapper) GetAuthor(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id int

	err = runtime.BindStyledParameterWithLocation("simple", false, "id", runtime.ParamLocationPath, ctx.Param("id"), &id)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetAuthor(ctx, id)
	return err
}

// UpdateAuthor converts echo context to params.
func (w *ServerInterfaceWrapper) UpdateAuthor(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id int

	err = runtime.BindStyledParameterWithLocation("simple", false, "id", runtime.ParamLocationPath, ctx.Param("id"), &id)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.UpdateAuthor(ctx, id)
	return err
}

// GetBooksByAuthor converts echo context to params.
func (w *ServerInterfaceWrapper) GetBooksByAuthor(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id int

	err = runtime.BindStyledParameterWithLocation("simple", false, "id", runtime.ParamLocationPath, ctx.Param("id"), &id)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetBooksByAuthor(ctx, id)
	return err
}

// ListBooks converts echo context to params.
func (w *ServerInterfaceWrapper) ListBooks(ctx echo.Context) error {
	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params ListBooksParams
	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameter("form", true, false, "page", ctx.QueryParams(), &params.Page)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter page: %s", err))
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", ctx.QueryParams(), &params.Limit)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter limit: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ListBooks(ctx, params)
	return err
}

// CreateBook converts echo context to params.
func (w *ServerInterfaceWrapper) CreateBook(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.CreateBook(ctx)
	return err
}

// DeleteBook converts echo context to params.
func (w *ServerInterfaceWrapper) DeleteBook(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id int

	err = runtime.BindStyledParameterWithLocation("simple", false, "id", runtime.ParamLocationPath, ctx.Param("id"), &id)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.DeleteBook(ctx, id)
	return err
}

// GetBook converts echo context to params.
func (w *ServerInterfaceWrapper) GetBook(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id int

	err = runtime.BindStyledParameterWithLocation("simple", false, "id", runtime.ParamLocationPath, ctx.Param("id"), &id)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetBook(ctx, id)
	return err
}

// UpdateBook converts echo context to params.
func (w *ServerInterfaceWrapper) UpdateBook(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id int

	err = runtime.BindStyledParameterWithLocation("simple", false, "id", runtime.ParamLocationPath, ctx.Param("id"), &id)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.UpdateBook(ctx, id)
	return err
}

// AssignAuthorToBook converts echo context to params.
func (w *ServerInterfaceWrapper) AssignAuthorToBook(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id int

	err = runtime.BindStyledParameterWithLocation("simple", false, "id", runtime.ParamLocationPath, ctx.Param("id"), &id)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.AssignAuthorToBook(ctx, id)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithBaseURL(router, si, "")
}

// Registers handlers, and prepends BaseURL to the paths, so that the paths
// can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.GET(baseURL+"/authors", wrapper.ListAuthors)
	router.POST(baseURL+"/authors", wrapper.CreateAuthor)
	router.DELETE(baseURL+"/authors/:id", wrapper.DeleteAuthor)
	router.GET(baseURL+"/authors/:id", wrapper.GetAuthor)
	router.PUT(baseURL+"/authors/:id", wrapper.UpdateAuthor)
	router.GET(baseURL+"/authors/:id/books", wrapper.GetBooksByAuthor)
	router.GET(baseURL+"/books", wrapper.ListBooks)
	router.POST(baseURL+"/books", wrapper.CreateBook)
	router.DELETE(baseURL+"/books/:id", wrapper.DeleteBook)
	router.GET(baseURL+"/books/:id", wrapper.GetBook)
	router.PUT(baseURL+"/books/:id", wrapper.UpdateBook)
	router.PUT(baseURL+"/books/:id/author", wrapper.AssignAuthorToBook)

}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+RYUU/cMAz+K1W2x4oeG0/3dgwJIU1oD9sTQijX+u4MbRISl6k69b9PSVpaIK2ubHeA",
	"9tQ2sWN/n+3Y6palslBSgCDD5ltm0g0U3L0ujMG1WJS0kdp+Ky0VaEJwu9yt32BmP6hSwOYMBcEaNKvr",
	"mGm4L1FDxuZXPdnruJWVy1tIidUxG7KwRNk725BGsbbyYZMxE7yAgEIdMHkq5d0QJPv2WcOKzdmnpCMn",
	"aZhJGnfreJyCYT9VuczRbCC7qYDrsAwh5buCuYTfUykcpqofNid1HbY4xuDNnpD3ffNi8WhqWR0UK0+B",
	"P5Z9x6XmuooWOt3gA0SLHxcsZg+gDUrB5uz4aHY0s35IBYIrZHP21S3FTHHaOJSJN+re10D2YUnghFJc",
	"ZM6IoUUjY/U0L4DAKlxtGVoz9yXoirWBYIqvLRifYuGCCivmWCCNa15b4oySwvgYfZnN7COVgkA457lS",
	"OabO/eTWWBq2vQORoDC7F0Vjn2vNKx+CDEyqUZEneBHlaCiSq6hl0cqYsii4rhruIp7n3XbMlDQBlr9p",
	"4ASNZZ8dYOhUZtUkfGOwutKqnyYg6RLqF8Qe/zPDfatP+fOos2es+dWIi4Y2t93mabLFrLYWM8iB4CWT",
	"Z279kclQwtrk79IOM/acjYk5eOL96SPzXmQ24Ceh/UtJ0UqW4jl2r9fHHofL8hzooBhnB0iHRWRQrHPo",
	"YZ9E3jlQx1y0rKKLM39TB/j7pTK+/zR58yo+RNg8ldNz3euN1XmylPJuuDWdA9nWbU6rd1wKO7UcN4FM",
	"ajiOGZvjtEHzVwWT591h/UCMc29bmyP/PxkKXhmhoYGg2RwfB5zNvV0jHtFhR4HO5pRBwLHVS8odZ4CG",
	"vreeAIL9vYEUj15sH661D4X3sbG3qKffUk51p56+X+beuBT3H6vHbh7s1cFSTLqfDcG49H++/JQfLT5P",
	"fh29kyB5byLuXHvF6OUxtZMyyTasdf0nAAD//2rAsr9EEwAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
